services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=login_projekt
      - MYSQL_USER=login
      - MYSQL_PASSWORD=login
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
  www:
    image: php:apache
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306